/*
 * File: CandidateClass.ui.js
 * Date: Sun Jun 05 2011 10:23:52 GMT-0400 (EDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

CandidateClassUi = Ext.extend(Ext.Panel, {
    title: 'Candidates',
    width: 576,
    layout: 'border',
    hideBorders: true,
    initComponent: function() {
        this.items = [
            {
                xtype: 'panel',
                region: 'center',
                layout: 'border',
                hideBorders: true,
                items: [
                    {
                        region: 'center',
                        ref: '../grid',
                        xtype: 'candidategrid'
                    },
                    {
                        xtype: 'panel',
                        region: 'south',
                        width: 250,
                        collapsible: true,
                        floatable: false,
                        split: true,
                        titleCollapse: true,
                        layout: 'fit',
                        hideBorders: true,
                        border: false,
                        height: 250,
                        items: [
                            {
                                xtype: 'tabpanel',
                                activeTab: 0,
                                border: false,
                                hideBorders: true,
                                deferredRender: false,
                                items: [
                                    {
                                        xtype: 'panel',
                                        title: 'Events',
                                        layout: 'fit',
                                        hideBorders: true,
                                        border: false,
                                        autoScroll: true,
                                        items: [
                                            {
                                                ref: '../../../../macgrid',
                                                xtype: 'candidatemacgrid'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        title: 'Candidate',
                                        layout: 'fit',
                                        frame: true,
                                        autoScroll: true,
                                        hideBorders: true,
                                        border: false,
                                        items: [
                                            {
                                                ref: '../../../../personaleditform',
                                                xtype: 'candidatepersonaleditform'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        title: 'Experience',
                                        layout: 'fit',
                                        frame: true,
                                        autoScroll: true,
                                        hideBorders: true,
                                        border: false,
                                        items: [
                                            {
                                                ref: '../../../../experienceeditform',
                                                xtype: 'candidateexperienceeditform'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        title: 'Files',
                                        autoScroll: true,
                                        layout: 'fit',
                                        items: [
                                            {
                                                ref: '../../../../candidatefilegrid',
                                                xtype: 'candidatefilegrid'
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'panel',
                width: 400,
                height: 250,
                region: 'east',
                tpl: '',
                collapsible: true,
                split: true,
                hideBorders: true,
                border: false,
                autoScroll: true,
                ref: 'infopanel'
            }
        ];
        CandidateClassUi.superclass.initComponent.call(this);
    }
});
