/*
 * File: CandidateStore.js
 * Date: Wed Jun 01 2011 08:49:10 GMT-0400 (EDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

CandidateStore = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        CandidateStore.superclass.constructor.call(this, Ext.apply({
            storeId: 'CandidateStore',
            root: 'results',
            url: '/ats/main/candidate/list/',
            restful: true,
            remoteSort: true,
            baseParams: {
                start: "0",
                limit: "15"
            },
            fields: [
                {
                    name: 'id',
                    mapping: 'pk',
                    type: 'int'
                },
                {
                    name: 'first_name',
                    mapping: 'fields["first_name"]',
                    type: 'string'
                },
                {
                    name: 'created_by__username',
                    mapping: 'fields["created_by"]["fields"]["username"]',
                    type: 'string'
                },
                {
                    name: 'updated_by__username',
                    mapping: 'fields["updated_by"]["fields"]["username"]',
                    type: 'string'
                },
                {
                    name: 'last_name',
                    mapping: 'fields["last_name"]',
                    type: 'string'
                },
                {
                    name: 'phone',
                    mapping: 'fields["phone"]',
                    type: 'string'
                },
                {
                    name: 'phone_extension',
                    mapping: 'fields["phone_extension"]',
                    type: 'string'
                },
                {
                    name: 'mobile',
                    mapping: 'fields["mobile"]',
                    type: 'string'
                },
                {
                    name: 'email_1',
                    mapping: 'fields["email_1"]',
                    type: 'string'
                },
                {
                    name: 'email_2',
                    mapping: 'fields["email_2"]',
                    type: 'string'
                },
                {
                    name: 'address',
                    mapping: 'fields["address"]',
                    type: 'string'
                },
                {
                    name: 'city',
                    mapping: 'fields["city"]',
                    type: 'string'
                },
                {
                    name: 'state',
                    mapping: 'fields["state"]',
                    type: 'string'
                },
                {
                    name: 'postal_code',
                    mapping: 'fields["postal_code"]',
                    type: 'string'
                },
                {
                    name: 'professional_designations',
                    mapping: 'fields["professional_designations"]'
                },
                {
                    name: 'managment_experience',
                    mapping: 'fields["managment_experience"]'
                },
                {
                    name: 'work_locations',
                    mapping: 'fields["work_locations"]'
                },
                {
                    name: 'work_types',
                    mapping: 'fields["work_types"]'
                },
                {
                    name: 'salary',
                    mapping: 'fields["salary"]'
                },
                {
                    name: 'keywords',
                    mapping: 'fields["keywords"]',
                    type: 'string'
                },
                {
                    name: 'employer',
                    mapping: 'fields["employer"]',
                    type: 'string'
                },
                {
                    name: 'resume',
                    type: 'string',
                    mapping: 'fields["resume"]',
                    defaultValue: ''
                }
            ]
        }, cfg));
    }
});
Ext.reg('candidatestore', CandidateStore);new CandidateStore();