/*
 * File: CandidateGridView.ui.js
 * Date: Wed Sep 29 2010 22:24:44 GMT-0400 (EDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

CandidateGridViewUi = Ext.extend(Ext.grid.GridView, {
    constructor: function(cfg) {
        cfg = cfg || {};
        CandidateGridViewUi.superclass.constructor.call(this, Ext.apply({
            forceFit: true,
            enableRowBody: true
        }, cfg));
    }
});
