/*
 * File: CandidateFileNewWindow.ui.js
 * Date: Thu Jun 09 2011 08:24:48 GMT-0400 (EDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

CandidateFileNewWindowUi = Ext.extend(Ext.Window, {
    title: 'New File',
    width: 400,
    layout: 'fit',
    autoHeight: true,
    collapsible: true,
    initHidden: false,
    hideBorders: true,
    maskDisabled: false,
    initComponent: function() {
        this.items = [
            {
                xtype: 'form',
                fileUpload: true,
                collapseFirst: false,
                autoHeight: true,
                labelWidth: 30,
                ref: 'form',
                items: [
                    {
                        xtype: 'hidden',
                        fieldLabel: 'Label',
                        anchor: '100%',
                        name: 'candidate',
                        ref: '../candidate'
                    },
                    {
                        xtype: 'textfield',
                        fieldLabel: 'Title',
                        anchor: '95%',
                        msgTarget: 'side',
                        name: 'title',
                        hidden: true,
                        hideLabel: true
                    },
                    {
                        xtype: 'progress',
                        hidden: true,
                        ref: '../progressbar'
                    }
                ],
                bbar: {
                    xtype: 'toolbar',
                    buttonAlign: 'center',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Upload File',
                            ref: '../../createbutton'
                        }
                    ]
                }
            }
        ];
        CandidateFileNewWindowUi.superclass.initComponent.call(this);
    }
});
