/*
 * File: CandidatePersonalEditForm.ui.js
 * Date: Sun Jun 05 2011 10:23:52 GMT-0400 (EDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

CandidatePersonalEditFormUi = Ext.extend(Ext.form.FormPanel, {
    autoHeight: true,
    padding: '0 50 0 5',
    border: false,
    animCollapse: false,
    hideBorders: true,
    autoWidth: true,
    initComponent: function() {
        this.items = [
            {
                xtype: 'hidden',
                fieldLabel: 'Label',
                name: 'id'
            },
            {
                xtype: 'compositefield',
                hideLabel: true,
                submitValue: false,
                items: [
                    {
                        xtype: 'displayfield',
                        value: 'First Name',
                        fieldLabel: 'Label',
                        submitValue: false,
                        width: 100
                    },
                    {
                        xtype: 'textfield',
                        name: 'first_name',
                        flex: 1,
                        fieldLabel: 'First Name',
                        growMax: 100,
                        maxLength: 50,
                        allowBlank: false
                    },
                    {
                        xtype: 'displayfield',
                        value: 'Last Name',
                        fieldLabel: 'Label',
                        submitValue: false,
                        width: 100
                    },
                    {
                        xtype: 'textfield',
                        name: 'last_name',
                        flex: 1,
                        fieldLabel: 'Last Name',
                        growMax: 100,
                        maxLength: 50,
                        allowBlank: false
                    }
                ]
            },
            {
                xtype: 'compositefield',
                submitValue: false,
                hideLabel: true,
                items: [
                    {
                        xtype: 'compositefield',
                        fieldLabel: 'Label',
                        flex: 1,
                        items: [
                            {
                                xtype: 'displayfield',
                                value: 'Phone',
                                fieldLabel: 'Label',
                                submitValue: false,
                                width: 100
                            },
                            {
                                xtype: 'textfield',
                                flex: 4,
                                fieldLabel: 'Phone',
                                name: 'phone',
                                maskRe: /[0-9-]/
                            },
                            {
                                xtype: 'displayfield',
                                value: 'Ext',
                                fieldLabel: 'Label',
                                submitValue: false,
                                flex: 1
                            },
                            {
                                xtype: 'textfield',
                                flex: 2,
                                fieldLabel: 'Ext',
                                name: 'phone_extension',
                                maxLength: 6,
                                maskRe: /[0-9-]/,
                                width: 50
                            }
                        ]
                    },
                    {
                        xtype: 'compositefield',
                        flex: 1,
                        fieldLabel: 'Label',
                        items: [
                            {
                                xtype: 'displayfield',
                                value: 'Mobile',
                                fieldLabel: 'Label',
                                submitValue: false,
                                width: 100,
                                flex: 1
                            },
                            {
                                xtype: 'textfield',
                                flex: 6,
                                fieldLabel: 'Mobile',
                                name: 'mobile',
                                maskRe: /[0-9-]/
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'compositefield',
                name: 'emails',
                submitValue: false,
                hideLabel: true,
                items: [
                    {
                        xtype: 'displayfield',
                        value: 'EMail 1',
                        flex: 1,
                        fieldLabel: 'Label',
                        submitValue: false,
                        width: 100
                    },
                    {
                        xtype: 'textfield',
                        flex: 1,
                        fieldLabel: 'EMail 1',
                        name: 'email_1',
                        vtype: 'email',
                        vtypeText: ''
                    },
                    {
                        xtype: 'displayfield',
                        value: 'EMail 2',
                        fieldLabel: 'Label',
                        width: 100,
                        submitValue: false
                    },
                    {
                        xtype: 'textfield',
                        flex: 1,
                        fieldLabel: 'EMail 2',
                        name: 'email_2',
                        vtype: 'email',
                        regex: /^([\w]+)(.[\w]+)*@([\w-]+\.){1,5}([A-Za-z]){2,4}$/
                    }
                ]
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Address',
                name: 'address',
                anchor: '100%',
                maxLength: 80
            },
            {
                xtype: 'compositefield',
                fieldLabel: 'City, State and Postal Code',
                hideLabel: true,
                items: [
                    {
                        xtype: 'compositefield',
                        flex: 1,
                        items: [
                            {
                                xtype: 'displayfield',
                                value: 'City',
                                fieldLabel: 'Label',
                                submitValue: false,
                                width: 100
                            },
                            {
                                xtype: 'textfield',
                                flex: 2,
                                fieldLabel: 'Label',
                                name: 'city',
                                maxLength: 80
                            }
                        ]
                    },
                    {
                        xtype: 'compositefield',
                        fieldLabel: 'Label',
                        flex: 1,
                        items: [
                            {
                                xtype: 'displayfield',
                                value: 'State',
                                fieldLabel: 'Label',
                                submitValue: false,
                                width: 100
                            },
                            {
                                xtype: 'textfield',
                                name: 'state',
                                flex: 1,
                                maxLength: 80
                            },
                            {
                                xtype: 'displayfield',
                                value: 'Postal Code',
                                fieldLabel: 'Label',
                                submitValue: false
                            },
                            {
                                xtype: 'textfield',
                                fieldLabel: 'Label',
                                name: 'postal_code',
                                flex: 1,
                                maxLength: 80
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Employer',
                anchor: '100%',
                name: 'employer'
            }
        ];
        this.fbar = {
            xtype: 'toolbar',
            autoWidth: true,
            items: [
                {
                    xtype: 'button',
                    text: 'Save',
                    ref: '../updatebutton'
                },
                {
                    xtype: 'button',
                    text: 'Save As New',
                    hidden: true,
                    width: 75,
                    ref: '../createbutton'
                },
                {
                    xtype: 'spacer',
                    width: 50
                }
            ]
        };
        CandidatePersonalEditFormUi.superclass.initComponent.call(this);
    }
});
