/*
 * File: CandidateFileUploadPanel.ui.js
 * Date: Thu Nov 18 2010 08:19:21 GMT-0500 (EST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

CandidateFileUploadPanelUi = Ext.extend(Ext.Panel, {
    initComponent: function() {
        this.items = [
            {
                xtype: 'grid',
                title: 'My Grid',
                store: 'CandidateFileStore',
                autoHeight: true,
                columns: [
                    {
                        xtype: 'gridcolumn',
                        dataIndex: 'title',
                        header: 'Title',
                        sortable: true,
                        width: 100
                    },
                    {
                        xtype: 'datecolumn',
                        dataIndex: 'created_time',
                        header: 'Date',
                        sortable: true,
                        width: 100,
                        format: 'Y-m-d'
                    },
                    {
                        xtype: 'templatecolumn',
                        header: 'Column',
                        sortable: true,
                        width: 100,
                        tpl: '<a href="{download_link}">Download</a>',
                        dataIndex: 'download_link'
                    }
                ]
            }
        ];
        CandidateFileUploadPanelUi.superclass.initComponent.call(this);
    }
});
