/*
 * File: CandidateFileUploadPanel.js
 * Date: Tue Nov 16 2010 20:46:38 GMT-0500 (EST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

CandidateFileUploadPanel = Ext.extend(CandidateFileUploadPanelUi, {
    initComponent: function() {
        CandidateFileUploadPanel.superclass.initComponent.call(this);

        this.fileuploadfield = new Ext.ux.form.FileUploadField({
             emptyText: 'Select a file'
            ,fieldLabel: 'File'
            ,name: 'file'
            ,buttonText: 'Browse'
            ,anchor: '95%'
            ,allowBlank: false
            ,msgTarget: 'side'
            });
        
        this.createbutton.on('click', this.onCreateClick, this );

    }
    ,onRender: function(ct, position) {
        CandidateFileUploadPanel.superclass.onRender.call(this, ct, position);
        this.form.add( this.fileuploadfield );
    }
    ,onCreateClick: function( button, event ) {
        var form = this.form.getForm();
        if( form.isValid() ){
            form.submit({
                 url: '/ats/main/data/candidate/file/new/'
                ,scope: this
                ,waitMsg: 'Uploading new file...'
                ,success: this.onSuccess
                ,failure: this.onFailure
            });
        }
    }
    ,onSuccess: function( form, action ) {
        //Ext.StoreMgr.lookup('CandidateFileStore').reload();
        Ext.example.msg('Success','File uploaded correctly.');
    }
    ,onFailure: function( form, action ) {
        switch ( action.failureType ) {
            case Ext.form.Action.CLIENT_INVALID:
                this.onClientInvalid( form, action);
            break;
            case Ext.form.Action.CONNECT_FAILURE:
                this.onConnectionFailure(form, action);
            break;
            case Ext.form.Action.SERVER_INVALID:
                this.onServerInvalid(form, action);
            break;
        };
    }
    ,onClientInvalid: function( form, action ) {
        Ext.Msg.alert('Failure',
                      'Fields may not be submitted with invalid values');
    } 
    ,onConnectionFailure: function( form, action ) {
        Ext.Msg.alert('Failure', 
                      'Ajax communication failed');
    }
    ,onServerInvalid: function( form, action ) {
        Ext.Msg.alert('Failure', action.result.msg);
    }

});
Ext.reg('candidatefileuploadpanel', CandidateFileUploadPanel);
