/*
 * File: CandidateFileNewWindow.js
 * Date: Wed Nov 17 2010 00:22:43 GMT-0500 (EST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

CandidateFileNewWindow = Ext.extend(CandidateFileNewWindowUi, {
    initComponent: function() {
        CandidateFileNewWindow.superclass.initComponent.call(this);

        win = this;
        this.createbutton.on('click', this.onCreateClick, this );
     }
    ,onRender: function(ct, position) {
        CandidateFileNewWindow.superclass.onRender.call(this, ct, position);
        //create field to browse for file in computer
        this.fileuploadfield = new Ext.ux.form.FileUploadField({
                 emptyText: 'Select a file'
                ,fieldLabel: 'File'
                ,name: 'file'
                ,buttonText: 'Browse'
                ,anchor: '95%'
                ,allowBlank: false
                ,msgTarget: 'side'
                });
        this.form.add( this.fileuploadfield );
    }
    ,onCreateClick: function( button, event ) {
        var form = this.form.getForm();
        if( form.isValid() ){
            form.submit({
                 url: '/ats/main/candidatefile/new/'
                ,scope: this
                //,waitMsg: 'Uploading new file...'
                ,success: this.onSuccess
                ,failure: this.onFailure
            });
            this.createbutton.disable();
            //leave just progressbar in form
            this.fileuploadfield.hide();
            this.fileuploadfield.label.hide();
            this.fileuploadfield.button.hide();
            this.progressbar.show();
            this.progressbar.wait({ 
                'text': this.fileuploadfield.getValue() 
                });
        }
    }
    ,onSuccess: function( form, action ) {
        Ext.StoreMgr.lookup('CandidateFileStore').reload();
        Ext.example.msg( 'Success', this.title + ' Uploaded!.' );
        this.close();
    }
    ,onFailure: function( form, action ) {
        this.createbutton.enable();
        switch ( action.failureType ) {
            case Ext.form.Action.CLIENT_INVALID:
                this.onClientInvalid( form, action);
            break;
            case Ext.form.Action.CONNECT_FAILURE:
                this.onConnectionFailure(form, action);
            break;
            case Ext.form.Action.SERVER_INVALID:
                this.onServerInvalid(form, action);
            break;
        };
    }
    ,onClientInvalid: function( form, action ) {
        Ext.Msg.alert('Failure',
                      'Fields may not be submitted with invalid values');
    } 
    ,onConnectionFailure: function( form, action ) {
        Ext.Msg.alert('Failure', 
                      'Ajax communication failed');
    }
    ,onServerInvalid: function( form, action ) {
        Ext.Msg.alert('Failure', action.result.msg);
    }


});
Ext.reg('candidatefilenewwindow', CandidateFileNewWindow);
