/*
 * File: CandidateFileGrid.ui.js
 * Date: Sun Jun 05 2011 10:23:52 GMT-0400 (EDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

CandidateFileGridUi = Ext.extend(Ext.grid.GridPanel, {
    store: 'CandidateFileStore',
    border: false,
    hideBorders: true,
    loadMask: true,
    stripeRows: true,
    initComponent: function() {
        this.viewConfig = {
            forceFit: true
        };
        this.selModel = new Ext.grid.RowSelectionModel({
            singleSelect: true
        });
        this.columns = [
            {
                xtype: 'gridcolumn',
                dataIndex: 'title',
                header: 'Title',
                sortable: true,
                width: 300
            },
            {
                xtype: 'datecolumn',
                dataIndex: 'created_time',
                header: 'Date',
                sortable: true,
                width: 75,
                format: 'Y-m-d',
                fixed: true
            },
            {
                xtype: 'templatecolumn',
                header: 'Download',
                sortable: false,
                width: 75,
                tpl: '<a href="{download_link}">Download</a>',
                dataIndex: 'download_link',
                fixed: true
            }
        ];
        this.tbar = {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'button',
                    text: 'New File',
                    tooltip: 'Upload a new file',
                    iconCls: 'img_add',
                    ref: '../newbutton'
                },
                {
                    xtype: 'button',
                    text: 'Delete File',
                    tooltip: 'Delete selected file',
                    iconCls: 'img_delete',
                    ref: '../deletebutton'
                },
                {
                    xtype: 'button',
                    text: 'Set Resume',
                    tooltip: 'Set resume from selected file',
                    iconCls: 'img_file',
                    ref: '../resumebutton'
                }
            ]
        };
        CandidateFileGridUi.superclass.initComponent.call(this);
    }
});
