/*
 * File: CandidateNewWindow.ui.js
 * Date: Sun Jun 05 2011 10:23:52 GMT-0400 (EDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

CandidateNewWindowUi = Ext.extend(Ext.Window, {
    title: 'New Candidate',
    width: 434,
    layout: 'fit',
    autoHeight: true,
    collapsible: true,
    initHidden: false,
    initComponent: function() {
        this.items = [
            {
                xtype: 'form',
                autoHeight: true,
                hideBorders: true,
                layout: 'auto',
                ref: 'form',
                items: [
                    {
                        xtype: 'fieldset',
                        labelWidth: 35,
                        padding: 5,
                        autoHeight: true,
                        items: [
                            {
                                xtype: 'textfield',
                                name: 'first_name',
                                anchor: '95%',
                                fieldLabel: 'First Name',
                                allowBlank: false
                            },
                            {
                                xtype: 'textfield',
                                fieldLabel: 'Last Name',
                                anchor: '95%',
                                name: 'last_name',
                                allowBlank: false
                            },
                            {
                                xtype: 'textfield',
                                fieldLabel: 'Phone',
                                anchor: '95%',
                                name: 'phone'
                            },
                            {
                                xtype: 'textfield',
                                fieldLabel: 'Mobile',
                                anchor: '95%',
                                name: 'mobile'
                            },
                            {
                                xtype: 'textfield',
                                fieldLabel: 'EMail',
                                anchor: '95%',
                                name: 'email_1',
                                vtype: 'email'
                            }
                        ],
                        fbar: {
                            xtype: 'toolbar',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Cancel',
                                    ref: '../../../cancelbutton'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Create',
                                    ref: '../../../createbutton'
                                }
                            ]
                        }
                    }
                ]
            }
        ];
        CandidateNewWindowUi.superclass.initComponent.call(this);
    }
});
