/*
 * File: CandidateClass.js
 * Date: Sat Jul 31 2010 15:46:13 GMT-0400 (EDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.11.
 * http://www.extjs.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

CandidateClass = Ext.extend(CandidateClassUi, {
    initComponent: function() {
        CandidateClass.superclass.initComponent.call(this);
        
        var sm = this.grid.getSelectionModel();
        sm.on( 'selectionchange'
              ,this.onGridRowSelectionChange
              ,this
              ,{ buffer:250 } );

        var sm = this.macgrid.getSelectionModel();
        sm.on( 'selectionchange'
              ,this.onMACGridRowSelectionChange
              ,this
              ,{ buffer:250 } );
    }
    ,resetSubGrids: function() {
        this.macgrid.store.removeAll();
        this.candidatefilegrid.store.removeAll();
        this.macgrid.store.lastOptions = {};
        this.candidatefilegrid.store.lastOptions = {};
    }
    ,updateSubGrids: function( record ) {
        //loads sub grids
        this.macgrid.store.setBaseParam( 'candidate__id'
                                         ,record.data["id"] );
        this.candidatefilegrid.store.setBaseParam( 'candidate__id'
                                                  ,record.data["id"] );
        this.macgrid.store.load();
        this.candidatefilegrid.store.load();
    }
    ,resetInfoPanel: function() {
        this.infopanel.tpl = null;
        this.infopanel.update( {} );
    }
    ,updateInfoPanel: function( tpl, record ) {
       this.infopanel.tpl = tpl;
       this.infopanel.update( record.data );
    }
    ,resetForms: function () {
        this.personaleditform.getForm().reset();
        this.experienceeditform.getForm().reset();
    }
    ,updateForms: function( record ) {
        this.personaleditform.populateRecord( record );
        this.experienceeditform.populateRecord( record );
    }
    ,onGridRowSelectionChange: function( sm ) {
       //Get selection
        if ( sm.getCount() == 1 ) {
            var record = sm.getSelected();
            this.updateInfoPanel( this.grid.infotpl, record );
            this.updateForms( record );
            this.updateSubGrids( record );
        } else {
            this.resetInfoPanel();
            this.resetForms();
            this.resetSubGrids();
        }
    }
    ,onMACGridRowSelectionChange: function( sm ) {
        //Get selection
        if ( sm.getCount()  == 1 ) {
            var record = sm.getSelected();
            this.updateInfoPanel( this.macgrid.infotpl, record );
        }
    }
});
Ext.reg('candidateclass', CandidateClass);
