/*
 * File: CandidateGrid.js
 * Date: Mon Aug 02 2010 00:10:34 GMT-0400 (EDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.11.
 * http://www.extjs.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

CandidateGrid = Ext.extend(CandidateGridUi, {
    initComponent: function() {
        CandidateGrid.superclass.initComponent.call(this);

        this.searchfield =  new Ext.ux.form.SearchField({
                 store: this.store
                 ,width: 350
            });

        //Template to display in any panel from a record of this.grid
        this.infotpl = new Ext.XTemplate(
            '<tpl for="."> <div class="preview">',
            ' <div class="info-data">',
            '  <h3 class="info-title">{first_name} {last_name}</h3>',
            ' </div>',
            ' <div class="info-body">{resume}</div>',
            '</div></tpl>',
            {
                compile: true
            }
            );

        //this.on('sortchange', this.onSortChange, this );
        //this.on('rowcontextmenu', this.onContextClick, this );
        this.newbutton.on('click', this.onNewClick, this );
        this.addmacbutton.on('click', this.onAddMACClick, this );
        this.macsbutton.on('click', this.onMACsClick, this );
        this.mandatesbutton.on('click', this.onMandatesClick, this );
    }
    ,onRender: function(ct, position) {
        CandidateGrid.superclass.onRender.call(this, ct, position);
        this.getTopToolbar().add(
            '->',
            'Search',
            ' ', 
            this.searchfield
            );
    }
    ,setQuery: function ( query ){
        this.searchfield.setQuery( query );
    }
    ,onNewClick: function ( button, event ){
        var win = new CandidateNewWindow();
        win.show();
    }
    ,onAddMACClick: function ( button, event ){
        var selected = this.selModel.getSelected();
        if ( !Ext.isEmpty( selected ) ){
            var win = new MACNewWindow();
            win.form.getForm().findField('candidate').setValue( 
                selected.data["id"]
            ); 
            win.show();
         }
    }
    ,onMACsClick: function ( button, event ){
        var selected = this.selModel.getSelected();
        if ( !Ext.isEmpty( selected ) ){
            candidate__id = selected.data["id"];
            //must go in MainTabPanelClass
            var mainpanel =  Ext.getCmp('maintabpanel');
            mainpanel.activate( mainpanel.mactab );
            mainpanel.mactab.grid.setQuery(
                { 'candidate': candidate__id }
            );
         }
    }
    ,onMandatesClick: function ( button, event ){
        var selected = this.selModel.getSelected();
        if ( !Ext.isEmpty( selected ) ){
            candidate__id = selected.data["id"];
            //must go in MainTabPanelClass
            var mainpanel =  Ext.getCmp('maintabpanel');
            mainpanel.activate( mainpanel.mandatetab );
            mainpanel.mandatetab.grid.setQuery(
                { 'candidate': candidate__id }
            );
         }
    }
 
});
Ext.reg('candidategrid', CandidateGrid);
