/*
 * File: HiringManagerStore.js
 * Date: Thu Jun 09 2011 08:24:48 GMT-0400 (EDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

HiringManagerStore = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        HiringManagerStore.superclass.constructor.call(this, Ext.apply({
            storeId: 'HiringManagerStore',
            url: '/ats/static/hiring_manager/list/',
            root: 'results',
            restful: true,
            fields: [
                {
                    name: 'id',
                    type: 'int',
                    mapping: 'pk'
                },
                {
                    name: 'name',
                    mapping: 'fields["name"]',
                    type: 'string'
                }
            ]
        }, cfg));
    }
});
Ext.reg('hiringmanagerstore', HiringManagerStore);new HiringManagerStore();