/*
 * File: MACClass.ui.js
 * Date: Thu Jun 09 2011 08:24:48 GMT-0400 (EDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

MACClassUi = Ext.extend(Ext.Panel, {
    title: 'Events',
    width: 576,
    layout: 'border',
    hideBorders: true,
    initComponent: function() {
        this.items = [
            {
                xtype: 'panel',
                region: 'center',
                layout: 'border',
                hideBorders: true,
                items: [
                    {
                        region: 'center',
                        ref: '../grid',
                        xtype: 'macgrid'
                    },
                    {
                        xtype: 'panel',
                        region: 'south',
                        width: 250,
                        collapsible: true,
                        floatable: false,
                        split: true,
                        titleCollapse: true,
                        layout: 'fit',
                        hideBorders: true,
                        border: false,
                        height: 250,
                        items: [
                            {
                                xtype: 'tabpanel',
                                activeTab: 0,
                                border: false,
                                hideBorders: true,
                                items: [
                                    {
                                        xtype: 'panel',
                                        title: 'Event',
                                        layout: 'fit',
                                        frame: true,
                                        autoScroll: true,
                                        hideBorders: true,
                                        items: [
                                            {
                                                ref: '../../../../editform',
                                                xtype: 'maceditform'
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'panel',
                width: 400,
                height: 250,
                region: 'east',
                tpl: [

                ],
                collapsible: true,
                split: true,
                hideBorders: true,
                border: false,
                autoScroll: true,
                ref: 'infopanel'
            },
            {
                xtype: 'panel',
                region: 'west',
                width: 250,
                autoScroll: true,
                collapsible: true,
                hideBorders: true,
                split: true,
                collapsed: true,
                ref: 'optionpanel',
                items: [
                    {
                        autoScroll: true,
                        xtype: 'macfilterpanel'
                    }
                ]
            }
        ];
        MACClassUi.superclass.initComponent.call(this);
    }
});
