/*
 * File: MACClass.js
 * Date: Mon Aug 09 2010 23:33:00 GMT-0400 (EDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.11.
 * http://www.extjs.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

MACClass = Ext.extend(MACClassUi, {
    initComponent: function() {
        MACClass.superclass.initComponent.call(this);

        var sm = this.grid.getSelectionModel();
        sm.on( 'selectionchange'
              ,this.onGridRowSelectionChange
              ,this
              ,{ buffer:250 } );

    }
    ,resetSubGrids: function() {
    }
    ,updateSubGrids: function( record ) {
    }
    ,resetInfoPanel: function() {
        this.infotpl = null;
        this.infopanel.update( {} );
    }
    ,updateInfoPanel: function( tpl, record ) {
       this.infopanel.tpl = tpl;
       this.infopanel.update( record.data );
    }
    ,resetForms: function() {
        //Reset forms
        this.editform.getForm().reset();
    }
    ,updateForms: function( record ){
        var editform = this.editform.getForm();
    	editform.loadRecord( record );
        //load select from objects
        if ( record.data.activity != null ) {
            editform.findField('activity').setValue(
                record.data.activity['pk'] 
            );
        }
        if ( record.data.status != null ) {
            editform.findField('status').setValue(
                record.data.status['pk'] 
            );
        }
        if ( record.data.candidate != null ) {
            editform.findField('candidate').setValue(
                record.data.candidate['pk'] 
            );
        }
        if ( record.data.mandate != null ) {
            editform.findField('mandate').setValue(
                record.data.mandate['pk'] 
            );
        }
    }
    ,onGridRowSelectionChange: function( sm ) {
        //reset forms
        this.resetForms();

        //Get selection
        if ( sm.getCount() > 0 ) {
            var record = sm.getSelected();
            this.updateForms( record );
            this.updateInfoPanel( this.grid.infotpl, record );
        }
    }

});
Ext.reg('macclass', MACClass);
