/*
 * File: MACEditWindow.js
 * Date: Mon May 09 2011 08:37:32 GMT-0400 (EDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

MACEditWindow = Ext.extend(MACEditWindowUi, {
    initComponent: function() {
        MACEditWindow.superclass.initComponent.call(this);
    }
});
Ext.reg('maceditwindow', MACEditWindow);