/*
 * File: MACEditForm.ui.js
 * Date: Sun Jun 05 2011 10:23:52 GMT-0400 (EDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

MACEditFormUi = Ext.extend(Ext.form.FormPanel, {
    autoHeight: true,
    padding: '10 10 10 10',
    border: false,
    animCollapse: false,
    hideBorders: true,
    autoWidth: true,
    initComponent: function() {
        this.items = [
            {
                xtype: 'hidden',
                name: 'id'
            },
            {
                xtype: 'hidden',
                fieldLabel: 'Label',
                anchor: '100%',
                name: 'candidate'
            },
            {
                xtype: 'hidden',
                fieldLabel: 'Label',
                anchor: '100%',
                name: 'mandate'
            },
            {
                xtype: 'compositefield',
                fieldLabel: 'Label',
                anchor: '100%',
                hideLabel: true,
                items: [
                    {
                        xtype: 'displayfield',
                        value: 'Activity',
                        fieldLabel: 'Label',
                        width: 100,
                        submitValue: false
                    },
                    {
                        xtype: 'combo',
                        name: 'activity',
                        store: 'ActivitiesStore',
                        valueField: 'id',
                        displayField: 'title',
                        forceSelection: true,
                        hiddenName: 'activity',
                        allowBlank: false,
                        mode: 'local',
                        triggerAction: 'all',
                        typeAhead: true,
                        flex: 2,
                        ref: '../cbactivity'
                    },
                    {
                        xtype: 'displayfield',
                        value: 'Status',
                        fieldLabel: 'Label',
                        submitValue: false,
                        flex: 1
                    },
                    {
                        xtype: 'combo',
                        name: 'status',
                        store: 'MACStatusStore',
                        valueField: 'id',
                        displayField: 'title',
                        forceSelection: true,
                        hiddenName: 'status',
                        allowBlank: false,
                        mode: 'local',
                        triggerAction: 'all',
                        typeAhead: true,
                        flex: 2,
                        ref: '../cbstatus'
                    },
                    {
                        xtype: 'displayfield',
                        value: 'Date',
                        fieldLabel: 'Label',
                        submitValue: false,
                        flex: 1
                    },
                    {
                        xtype: 'datefield',
                        name: 'date',
                        format: 'Y-m-d',
                        flex: 1
                    }
                ]
            },
            {
                xtype: 'textarea',
                anchor: '100%',
                fieldLabel: 'Description',
                name: 'description',
                height: 163
            }
        ];
        this.fbar = {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'button',
                    text: 'Save',
                    ref: '../updatebutton'
                },
                {
                    xtype: 'button',
                    text: 'Save as New',
                    ref: '../createbutton'
                },
                {
                    xtype: 'spacer',
                    width: 50
                }
            ]
        };
        MACEditFormUi.superclass.initComponent.call(this);
    }
});
