/*
 * File: MACFilterPanel.ui.js
 * Date: Thu Jun 09 2011 08:24:48 GMT-0400 (EDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

MACFilterPanelUi = Ext.extend(Ext.form.FormPanel, {
    title: 'Filters',
    labelAlign: 'top',
    padding: '5 5 5 5 ',
    border: false,
    autoScroll: true,
    initComponent: function() {
        this.items = [
            {
                xtype: 'textarea',
                name: 'description',
                fieldLabel: 'Description',
                anchor: '90%',
                ref: 'description'
            }
        ];
        this.fbar = {
            xtype: 'toolbar',
            buttonAlign: 'center',
            items: [
                {
                    xtype: 'button',
                    text: 'Reset',
                    ref: '../resetbutton'
                },
                {
                    xtype: 'button',
                    text: 'Apply',
                    ref: '../applybutton'
                }
            ]
        };
        MACFilterPanelUi.superclass.initComponent.call(this);
    }
});
