/*
 * File: MACGrid.ui.js
 * Date: Wed Jun 01 2011 08:49:10 GMT-0400 (EDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

MACGridUi = Ext.extend(Ext.grid.GridPanel, {
    store: 'MACStore',
    stripeRows: true,
    autoShow: true,
    border: false,
    hideBorders: true,
    id: 'mactab',
    initComponent: function() {
        this.selModel = new Ext.grid.RowSelectionModel({
            singleSelect: true
        });
        this.columns = [
            {
                xtype: 'gridcolumn',
                dataIndex: 'id',
                header: 'Event',
                sortable: true,
                width: 60,
                tooltip: 'Candidate ID',
                fixed: true,
                id: 'id'
            },
            {
                xtype: 'gridcolumn',
                header: 'Candidate',
                sortable: true,
                width: 60,
                dataIndex: 'candidate',
                fixed: true,
                id: 'candidate__id'
            },
            {
                xtype: 'gridcolumn',
                header: 'First Name',
                sortable: true,
                width: 100,
                dataIndex: 'candidate',
                id: 'candidate__first_name'
            },
            {
                xtype: 'gridcolumn',
                header: 'Last Name',
                sortable: true,
                width: 100,
                dataIndex: 'candidate',
                id: 'candidate__last_name'
            },
            {
                xtype: 'gridcolumn',
                header: 'Phone',
                sortable: true,
                width: 100,
                dataIndex: 'candidate',
                id: 'candidate__phone'
            },
            {
                xtype: 'datecolumn',
                header: 'Date',
                sortable: true,
                width: 75,
                dataIndex: 'date',
                format: 'Y-m-d',
                fixed: true,
                id: 'date'
            },
            {
                xtype: 'gridcolumn',
                header: 'Description',
                sortable: true,
                width: 200,
                dataIndex: 'description'
            }
        ];
        this.tbar = {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'button',
                    text: 'New',
                    iconCls: 'img_add_event',
                    scale: 'medium',
                    ref: '../newbutton'
                },
                {
                    xtype: 'button',
                    text: 'Candidate',
                    tooltip: 'Show cadidate for selected event',
                    iconCls: 'img_list_candidates',
                    scale: 'medium',
                    ref: '../candidatebutton'
                },
                {
                    xtype: 'button',
                    text: 'Mandate',
                    tooltip: 'Show mandate for selected event',
                    iconCls: 'img_list_mandates',
                    scale: 'medium',
                    ref: '../mandatebutton'
                }
            ]
        };
        this.items = [
            {
                xtype: 'toolbar',
                ref: 'extratb',
                items: [
                    {
                        xtype: 'label',
                        text: 'Extra Filters'
                    },
                    {
                        xtype: 'tbfill'
                    },
                    {
                        xtype: 'label',
                        text: 'From:'
                    },
                    {
                        xtype: 'datefield',
                        format: 'Y-m-d',
                        width: 100,
                        ref: '../extrafilterfromdate',
                        id: 'fromdate'
                    },
                    {
                        xtype: 'tbspacer',
                        width: 100
                    },
                    {
                        xtype: 'label',
                        text: 'To:'
                    },
                    {
                        xtype: 'datefield',
                        format: 'Y-m-d',
                        width: 100,
                        ref: '../extrafiltertodate',
                        id: 'todate'
                    },
                    {
                        xtype: 'tbspacer',
                        width: 100
                    },
                    {
                        xtype: 'button',
                        text: 'Apply',
                        ref: '../extrafilterapplybutton'
                    },
                    {
                        xtype: 'button',
                        text: 'Reset',
                        ref: '../extrafilterresetbutton'
                    }
                ]
            }
        ];
        this.bbar = {
            xtype: 'toolbar',
            buttonAlign: 'right',
            items: [
                {
                    xtype: 'paging',
                    store: 'MACStore',
                    pageSize: 15,
                    hideBorders: true,
                    displayInfo: true,
                    buttonAlign: 'right',
                    ref: '../pagingtoolbar'
                }
            ]
        };
        this.view = Ext.create({
            xtype: 'macgridview'
        });
        MACGridUi.superclass.initComponent.call(this);
    }
});
