/*
 * File: MACNewWindow.ui.js
 * Date: Wed Jun 01 2011 08:49:10 GMT-0400 (EDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

MACNewWindowUi = Ext.extend(Ext.Window, {
    title: 'New Event',
    width: 500,
    layout: 'fit',
    autoHeight: true,
    collapsible: true,
    initHidden: false,
    hideBorders: true,
    initComponent: function() {
        this.items = [
            {
                xtype: 'form',
                autoHeight: true,
                layout: 'auto',
                hideBorders: true,
                ref: 'form',
                items: [
                    {
                        xtype: 'fieldset',
                        padding: '',
                        autoHeight: true,
                        items: [
                            {
                                fieldLabel: 'Candidate',
                                anchor: '100%',
                                xtype: 'candidatecombobox'
                            },
                            {
                                fieldLabel: 'Mandate',
                                anchor: '100%',
                                xtype: 'mandatecombobox'
                            },
                            {
                                xtype: 'combo',
                                fieldLabel: 'Activity',
                                anchor: '100%',
                                name: 'activity__title',
                                store: 'ActivitiesStore',
                                valueField: 'id',
                                displayField: 'title',
                                forceSelection: true,
                                hiddenName: 'activity',
                                allowBlank: false,
                                mode: 'local',
                                submitValue: true,
                                triggerAction: 'all',
                                typeAhead: true,
                                ref: '../../cbactivity'
                            },
                            {
                                xtype: 'combo',
                                fieldLabel: 'Status',
                                anchor: '100%',
                                name: 'status__title',
                                store: 'MACStatusStore',
                                valueField: 'id',
                                displayField: 'title',
                                forceSelection: true,
                                hiddenName: 'status',
                                allowBlank: false,
                                mode: 'local',
                                submitValue: true,
                                triggerAction: 'all',
                                typeAhead: true,
                                ref: '../../cbstatus'
                            },
                            {
                                xtype: 'datefield',
                                fieldLabel: 'Date',
                                anchor: '100%',
                                name: 'date',
                                format: 'Y-m-d'
                            },
                            {
                                xtype: 'textarea',
                                anchor: '100%',
                                fieldLabel: 'Description',
                                name: 'description',
                                height: 163,
                                emptyText: 'description...',
                                hideLabel: true
                            }
                        ],
                        fbar: {
                            xtype: 'toolbar',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Cancel',
                                    ref: '../../../cancelbutton'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Create',
                                    ref: '../../../createbutton'
                                }
                            ]
                        }
                    }
                ]
            }
        ];
        MACNewWindowUi.superclass.initComponent.call(this);
    }
});
