/*
 * File: MainTabPanel.js
 * Date: Wed Aug 18 2010 01:40:54 GMT-0400 (EDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.11.
 * http://www.extjs.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

MainTabPanel = Ext.extend(MainTabPanelUi, {
    initComponent: function() {
        MainTabPanel.superclass.initComponent.call(this);
    }
});
Ext.reg('maintabpanel', MainTabPanel);