/*
 * File: MainTabPanel.ui.js
 * Date: Thu Jun 09 2011 08:24:48 GMT-0400 (EDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

MainTabPanelUi = Ext.extend(Ext.TabPanel, {
    activeTab: 0,
    width: 4738,
    height: 28,
    hideBorders: true,
    border: false,
    deferredRender: false,
    id: 'maintabpanel',
    initComponent: function() {
        this.items = [
            {
                xtype: 'webtopclass'
            },
            {
                ref: 'candidatetab',
                xtype: 'candidateclass'
            },
            {
                ref: 'mandatetab',
                xtype: 'mandateclass'
            },
            {
                ref: 'mactab',
                xtype: 'macclass'
            }
        ];
        MainTabPanelUi.superclass.initComponent.call(this);
    }
});
