/*
 * File: ManagmentExperienceStore.js
 * Date: Wed Jun 01 2011 08:49:10 GMT-0400 (EDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

ManagmentExperienceStore = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        ManagmentExperienceStore.superclass.constructor.call(this, Ext.apply({
            storeId: 'ManagmentExperienceStore',
            root: 'results',
            url: '/ats/static/managment_experience/list/',
            restful: true,
            fields: [
                {
                    name: 'id',
                    mapping: 'pk',
                    type: 'int'
                },
                {
                    name: 'title',
                    mapping: 'fields["title"]',
                    type: 'string'
                }
            ]
        }, cfg));
    }
});
Ext.reg('managmentexperiencestore', ManagmentExperienceStore);new ManagmentExperienceStore();