/*
 * File: MandateEditForm.ui.js
 * Date: Wed Jun 01 2011 08:49:10 GMT-0400 (EDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

MandateEditFormUi = Ext.extend(Ext.form.FormPanel, {
    autoHeight: true,
    padding: '0 50 0 5',
    border: false,
    animCollapse: false,
    autoWidth: true,
    hideBorders: true,
    initComponent: function() {
        this.items = [
            {
                xtype: 'hidden',
                fieldLabel: 'Label',
                name: 'id'
            },
            {
                xtype: 'hidden',
                fieldLabel: 'Label',
                anchor: '100%',
                name: 'form',
                value: 'mandateeditform'
            },
            {
                xtype: 'compositefield',
                anchor: '100%',
                hideLabel: true,
                submitValue: false,
                items: [
                    {
                        xtype: 'displayfield',
                        value: 'Title',
                        submitValue: false,
                        fieldLabel: 'Label',
                        width: 100
                    },
                    {
                        xtype: 'textfield',
                        name: 'title',
                        flex: 1
                    },
                    {
                        xtype: 'displayfield',
                        value: 'Posting Start',
                        submitValue: false,
                        width: 90
                    },
                    {
                        xtype: 'datefield',
                        name: 'posting_start_date',
                        format: 'Y-m-d',
                        flex: 1,
                        width: 150
                    }
                ]
            },
            {
                xtype: 'compositefield',
                anchor: '100%',
                hideLabel: true,
                submitValue: false,
                items: [
                    {
                        xtype: 'displayfield',
                        value: 'Hiring Manager',
                        submitValue: false,
                        width: 100
                    },
                    {
                        xtype: 'combo',
                        name: 'hiring_manager',
                        store: 'HiringManagerStore',
                        hiddenName: 'hiring_manager',
                        valueField: 'id',
                        displayField: 'name',
                        mode: 'local',
                        typeAhead: true,
                        allowBlank: false,
                        triggerAction: 'all',
                        flex: 2,
                        ref: '../cbhiringmanager'
                    },
                    {
                        xtype: 'displayfield',
                        value: 'Status',
                        submitValue: false,
                        fieldLabel: 'Label'
                    },
                    {
                        xtype: 'combo',
                        name: 'status',
                        store: 'MandateStatusStore',
                        valueField: 'id',
                        displayField: 'title',
                        forceSelection: true,
                        hiddenName: 'status',
                        allowBlank: false,
                        mode: 'local',
                        triggerAction: 'all',
                        typeAhead: true,
                        flex: 1,
                        ref: '../cbstatus'
                    },
                    {
                        xtype: 'displayfield',
                        value: 'Posting End',
                        fieldLabel: 'Label',
                        submitValue: false,
                        width: 90
                    },
                    {
                        xtype: 'datefield',
                        name: 'posting_end_date',
                        format: 'Y-m-d',
                        flex: 1,
                        width: 150
                    }
                ]
            },
            {
                xtype: 'compositefield',
                fieldLabel: 'Label',
                anchor: '100%',
                submitValue: false,
                hideLabel: true,
                items: [
                    {
                        xtype: 'displayfield',
                        value: 'City',
                        fieldLabel: 'Label',
                        submitValue: false,
                        width: 100
                    },
                    {
                        xtype: 'textfield',
                        flex: 1,
                        fieldLabel: 'Label',
                        name: 'city'
                    },
                    {
                        xtype: 'displayfield',
                        value: 'Posting Number',
                        fieldLabel: 'Label',
                        submitValue: false,
                        width: 90
                    },
                    {
                        xtype: 'textfield',
                        flex: 1,
                        fieldLabel: 'Label',
                        name: 'posting_number',
                        width: 150
                    }
                ]
            }
        ];
        this.fbar = {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'button',
                    text: 'Save',
                    ref: '../updatebutton'
                },
                {
                    xtype: 'button',
                    text: 'Save As New',
                    hidden: true,
                    width: 75,
                    ref: '../createbutton'
                },
                {
                    xtype: 'spacer',
                    width: 50
                }
            ]
        };
        MandateEditFormUi.superclass.initComponent.call(this);
    }
});
