/*
 * File: MandateEditDescForm.ui.js
 * Date: Sun Oct 24 2010 10:58:01 GMT-0400 (EDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

MandateEditDescFormUi = Ext.extend(Ext.form.FormPanel, {
    autoHeight: true,
    padding: 5,
    border: false,
    animCollapse: false,
    autoWidth: true,
    hideBorders: true,
    initComponent: function() {
        this.items = [
            {
                xtype: 'fieldset',
                padding: '',
                hideBorders: true,
                items: [
                    {
                        xtype: 'textarea',
                        anchor: '95%',
                        fieldLabel: 'Description',
                        name: 'description',
                        height: 163
                    },
                    {
                        xtype: 'hidden',
                        fieldLabel: 'Label',
                        name: 'id'
                    }
                ],
                fbar: {
                    xtype: 'toolbar',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Save',
                            ref: '../../updatebutton'
                        }
                    ]
                }
            }
        ];
        MandateEditDescFormUi.superclass.initComponent.call(this);
    }
});
