/*
 * File: MandateEditDescResponsabilityForm.js
 * Date: Sun Oct 24 2010 11:21:46 GMT-0400 (EDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

MandateEditDescResponsabilityForm = Ext.extend(MandateEditDescResponsabilityFormUi, {
    initComponent: function() {
        MandateEditDescResponsabilityForm.superclass.initComponent.call(this);
        this.updatebutton.on('click', this.onUpdateClick, this );
    }
    ,onUpdateClick: function( button, event ) {
        var form = this.getForm();
        if( form.isValid() ){
            form.submit({
                 url: '/ats/main/mandate/update/'
                ,scope: this
                ,waitMsg: 'Updating mandate...'
                ,success: this.onSuccess
                ,failure: this.onFailure
            });
        }
    }
    ,onSuccess: function( form, action ) {
        //Ext.StoreMgr.lookup('MandateStore').reload();
        Ext.example.msg('Success','Mandate upated correctly".');
        //Ext.Msg.show({
        //    title: 'Success'
        //    ,msg: 'Reload grid to see the changes!'
        //    ,modal: true
        //    ,icon: Ext.Msg.INFO
        //    ,buttons: Ext.Msg.OK
        //});
    }
    ,onFailure: function( form, action ) {
        switch ( action.failureType ) {
            case Ext.form.Action.CLIENT_INVALID:
                this.onClientInvalid( form, action);
            break;
            case Ext.form.Action.CONNECT_FAILURE:
                this.onConnectionFailure(form, action);
            break;
            case Ext.form.Action.SERVER_INVALID:
                this.onServerInvalid(form, action);
            break;
        };
    }
    ,onClientInvalid: function( form, action ) {
        Ext.Msg.alert('Failure',
                      'Form fields may not be submitted with invalid values');
    } 
    ,onConnectionFailure: function( form, action ) {
        Ext.Msg.alert('Failure', 
                      'Ajax communication failed');
    }
    ,onServerInvalid: function( form, action ) {
        Ext.Msg.alert('Failure', action.result.msg);
    }

});
Ext.reg('mandateeditdescresponsabilityform', MandateEditDescResponsabilityForm);
