/*
 * File: MandateNewWindow.ui.js
 * Date: Wed Jun 01 2011 08:49:10 GMT-0400 (EDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

MandateNewWindowUi = Ext.extend(Ext.Window, {
    title: 'New Mandate',
    width: 350,
    layout: 'fit',
    autoHeight: true,
    collapsible: true,
    initHidden: false,
    hideBorders: true,
    initComponent: function() {
        this.items = [
            {
                xtype: 'form',
                autoHeight: true,
                layout: 'auto',
                hideBorders: true,
                ref: 'form',
                items: [
                    {
                        xtype: 'fieldset',
                        labelWidth: 35,
                        padding: '',
                        autoHeight: true,
                        items: [
                            {
                                xtype: 'textfield',
                                fieldLabel: 'Title',
                                anchor: '100%',
                                name: 'title',
                                allowBlank: false,
                                growMax: 100,
                                maxLength: 50
                            }
                        ],
                        fbar: {
                            xtype: 'toolbar',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Cancel',
                                    ref: '../../../cancelbutton'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Create',
                                    ref: '../../../createbutton'
                                }
                            ]
                        }
                    }
                ]
            }
        ];
        MandateNewWindowUi.superclass.initComponent.call(this);
    }
});
