/*
 * File: MandateMACsStore.js
 * Date: Sun Jun 05 2011 10:23:52 GMT-0400 (EDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

MandateMACsStore = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        MandateMACsStore.superclass.constructor.call(this, Ext.apply({
            storeId: 'MandateMACsStore',
            url: '/ats/main/mac/list/',
            root: 'results',
            restful: true,
            remoteSort: true,
            fields: [
                {
                    name: 'candidate',
                    mapping: 'fields["candidate"]'
                },
                {
                    name: 'activity',
                    mapping: 'fields["activity"]'
                },
                {
                    name: 'status',
                    mapping: 'fields["status"]'
                },
                {
                    name: 'date',
                    mapping: 'fields["date"]',
                    type: 'date'
                },
                {
                    name: 'description',
                    mapping: 'fields["description"]'
                }
            ]
        }, cfg));
    }
});
Ext.reg('mandatemacsstore', MandateMACsStore);new MandateMACsStore();