/*
 * File: MandateGridView.ui.js
 * Date: Sun Jun 05 2011 10:23:52 GMT-0400 (EDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

MandateGridViewUi = Ext.extend(Ext.grid.GridView, {
    constructor: function(cfg) {
        cfg = cfg || {};
        MandateGridViewUi.superclass.constructor.call(this, Ext.apply({
            forceFit: true,
            enableRowBody: true
        }, cfg));
    }
});
