/*
 * File: MandateCandidatesStore.js
 * Date: Sun Jun 05 2011 10:23:52 GMT-0400 (EDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

MandateCandidatesStore = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        MandateCandidatesStore.superclass.constructor.call(this, Ext.apply({
            storeId: 'MandateCandidatesStore',
            url: '/ats/main/candidate/list/',
            root: 'results',
            restful: true,
            remoteSort: true,
            fields: [
                {
                    name: 'id',
                    type: 'int',
                    mapping: 'pk'
                },
                {
                    name: 'first_name',
                    type: 'string',
                    mapping: 'fields["first_name"]'
                },
                {
                    name: 'last_name',
                    type: 'string',
                    mapping: 'fields["last_name"]'
                },
                {
                    name: 'phone',
                    type: 'string',
                    mapping: 'fields["phone"]'
                }
            ]
        }, cfg));
    }
});
Ext.reg('mandatecandidatesstore', MandateCandidatesStore);new MandateCandidatesStore();