/*
 * File: MandateEditDescRequirementForm.ui.js
 * Date: Thu Jun 09 2011 08:24:48 GMT-0400 (EDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

MandateEditDescRequirementFormUi = Ext.extend(Ext.form.FormPanel, {
    autoHeight: true,
    border: false,
    animCollapse: false,
    autoWidth: true,
    hideBorders: true,
    initComponent: function() {
        this.items = [
            {
                xtype: 'fieldset',
                padding: '',
                hideBorders: true,
                items: [
                    {
                        xtype: 'htmleditor',
                        anchor: '100%',
                        height: 150,
                        fieldLabel: 'Label',
                        hideLabel: true,
                        name: 'requirement'
                    },
                    {
                        xtype: 'hidden',
                        fieldLabel: 'Label',
                        name: 'id'
                    },
                    {
                        xtype: 'hidden',
                        fieldLabel: 'Label',
                        anchor: '100%',
                        name: 'form',
                        value: 'mandaterequirementform'
                    }
                ],
                fbar: {
                    xtype: 'toolbar',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Save',
                            ref: '../../updatebutton'
                        }
                    ]
                }
            }
        ];
        MandateEditDescRequirementFormUi.superclass.initComponent.call(this);
    }
});
