/*
 * File: MandateMACGridView.ui.js
 * Date: Wed Jun 01 2011 08:49:10 GMT-0400 (EDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

MandateMACGridViewUi = Ext.extend(Ext.grid.GridView, {
    constructor: function(cfg) {
        cfg = cfg || {};
        MandateMACGridViewUi.superclass.constructor.call(this, Ext.apply({
            forceFit: true
        }, cfg));
    }
});
