/*
 * File: MandateClosingForm.ui.js
 * Date: Thu Jun 09 2011 08:24:48 GMT-0400 (EDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

MandateClosingFormUi = Ext.extend(Ext.form.FormPanel, {
    autoHeight: true,
    padding: '0 50 0 5',
    border: false,
    animCollapse: false,
    autoWidth: true,
    hideBorders: true,
    initComponent: function() {
        this.items = [
            {
                xtype: 'hidden',
                fieldLabel: 'Label',
                name: 'id'
            },
            {
                xtype: 'hidden',
                fieldLabel: 'Label',
                anchor: '100%',
                name: 'form',
                value: 'mandateclosingform'
            },
            {
                xtype: 'compositefield',
                fieldLabel: 'Label',
                anchor: '100%',
                submitValue: false,
                hideLabel: true,
                items: [
                    {
                        xtype: 'displayfield',
                        value: 'Candidate Source',
                        fieldLabel: 'Label',
                        submitValue: false,
                        width: 100,
                        flex: 1
                    },
                    {
                        xtype: 'textfield',
                        flex: 1,
                        fieldLabel: 'Label',
                        name: 'candidate_source'
                    },
                    {
                        xtype: 'displayfield',
                        value: 'Posting Sources',
                        fieldLabel: 'Label',
                        submitValue: false
                    },
                    {
                        xtype: 'textfield',
                        flex: 1,
                        fieldLabel: 'Label',
                        name: 'posting_sources'
                    }
                ]
            },
            {
                xtype: 'compositefield',
                fieldLabel: 'Label',
                anchor: '100%',
                submitValue: false,
                hideLabel: true,
                items: [
                    {
                        xtype: 'displayfield',
                        value: 'Start Date',
                        fieldLabel: 'Label',
                        submitValue: false,
                        width: 100
                    },
                    {
                        xtype: 'datefield',
                        fieldLabel: 'Label',
                        name: 'start_date',
                        flex: 2,
                        format: 'Y-m-d'
                    },
                    {
                        xtype: 'displayfield',
                        value: 'End Date',
                        fieldLabel: 'Label',
                        submitValue: false,
                        flex: 1
                    },
                    {
                        xtype: 'datefield',
                        fieldLabel: 'Label',
                        name: 'end_date',
                        flex: 2,
                        format: 'Y-m-d'
                    },
                    {
                        xtype: 'displayfield',
                        value: 'Consulting Time',
                        fieldLabel: 'Label',
                        submitValue: false,
                        flex: 1
                    },
                    {
                        xtype: 'numberfield',
                        fieldLabel: 'Label',
                        allowNegative: false,
                        flex: 1,
                        name: 'consulting_time',
                        decimalPrecision: 1
                    },
                    {
                        xtype: 'displayfield',
                        value: 'Hired Number',
                        fieldLabel: 'Label',
                        submitValue: false,
                        flex: 1
                    },
                    {
                        xtype: 'numberfield',
                        allowDecimals: false,
                        allowNegative: false,
                        flex: 1,
                        name: 'hired_number'
                    }
                ]
            },
            {
                xtype: 'textarea',
                anchor: '100%',
                fieldLabel: 'Comments',
                name: 'comments'
            }
        ];
        this.fbar = {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'button',
                    text: 'Save',
                    ref: '../updatebutton'
                },
                {
                    xtype: 'spacer',
                    width: 50
                }
            ]
        };
        MandateClosingFormUi.superclass.initComponent.call(this);
    }
});
