/*
 * File: SearchField.ui.js
 * Date: Sat Jul 31 2010 13:39:45 GMT-0400 (EDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.11.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

SearchFieldUi = Ext.extend(Ext.form.TriggerField, {
    width: 250,
    validateOnBlur: false,
    triggerClass: 'x-form-search-trigger',
    initComponent: function() {
        SearchFieldUi.superclass.initComponent.call(this);
    }
});
