/*
 * File: WebTopClass.ui.js
 * Date: Thu Jun 09 2011 08:24:48 GMT-0400 (EDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

WebTopClassUi = Ext.extend(Ext.Panel, {
    title: 'WebTop',
    layout: 'border',
    header: true,
    autoWidth: true,
    border: false,
    autoScroll: true,
    initComponent: function() {
        this.tpl = [
            'Coming soon!!!'
        ];
        this.items = [
            {
                xtype: 'panel',
                title: 'Coming soon!!!',
                region: 'center'
            }
        ];
        WebTopClassUi.superclass.initComponent.call(this);
    }
});
