/*
 * File: WebTopClass.js
 * Date: Sun Apr 03 2011 23:18:56 GMT-0400 (EDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

WebTopClass = Ext.extend(WebTopClassUi, {
    initComponent: function() {
        WebTopClass.superclass.initComponent.call(this);
    }
});
Ext.reg('webtopclass', WebTopClass);