/*
 * File: WorkTypeStore.js
 * Date: Sun Jun 05 2011 10:23:52 GMT-0400 (EDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

WorkTypeStore = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        WorkTypeStore.superclass.constructor.call(this, Ext.apply({
            storeId: 'WorkTypeStore',
            root: 'results',
            url: '/ats/static/work_type/list/',
            restful: true,
            fields: [
                {
                    name: 'id',
                    mapping: 'pk',
                    type: 'int'
                },
                {
                    name: 'title',
                    mapping: 'fields["title"]',
                    type: 'string'
                }
            ]
        }, cfg));
    }
});
Ext.reg('worktypestore', WorkTypeStore);new WorkTypeStore();