/*
 * File: xds_index.js
 * Date: Thu Jun 09 2011 08:24:48 GMT-0400 (EDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.onReady(function() {
    Ext.QuickTips.init();
    var cmp1 = new ATS({
        renderTo: Ext.getBody()
    });
    cmp1.show();
    var cmp2 = new CandidateNewWindow({
        renderTo: Ext.getBody()
    });
    cmp2.show();
    var cmp3 = new MandateNewWindow({
        renderTo: Ext.getBody()
    });
    cmp3.show();
    var cmp4 = new CandidateFileNewWindow({
        renderTo: Ext.getBody()
    });
    cmp4.show();
    var cmp5 = new MACNewWindow({
        renderTo: Ext.getBody()
    });
    cmp5.show();
    var cmp6 = new MACEditWindow({
        renderTo: Ext.getBody()
    });
    cmp6.show();
});
